server:
  port: 10601

graphql:
  servlet:
    mapping: /graphql

spring:
  profiles:
    active: @activatedProperties@

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.github.crazyjay97.entity
  global-config:
    db-config:
      id-type: none


