graphiql:
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newcloud?serverTimezone=GMT%2B8
    username: root
    password: Zz123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.github.crazyjay97.dao : debug